version: 0.0
os: linux
files:
 - source: .
   destination: /var/www/html/
file_exists_behavior: OVERWRITE
hooks:
  AfterInstall:
     - location: scripts/install.sh
       timeout: 150
       runas: root
