version: 0.0
os: linux
files:
 - source: .
   destination: /var/www/html/
file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
     - location: scripts/install.sh
       timeout: 150
       runas: root
  Install:
     - location: scripts/install.sh
       timeout: 150
       runas: root
  AfterInstall:
     - location: scripts/install.sh
       timeout: 150
       runas: root
  ApplicationStart:
     - location: scripts/install.sh
       timeout: 150
       runas: root 
  ValidateService:
     - location: scripts/install.sh
       timeout: 150
       runas: root